# Generated by Django 5.1.5 on 2025-01-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaicertificate',
            old_name='certifiacte_number',
            new_name='certificate_number',
        ),
    ]
